version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: turnoya_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: turnoya_db
      MYSQL_USER: turnouser
      MYSQL_PASSWORD: turnopass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: turnoya_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/turnoya_db
      SPRING_DATASOURCE_USERNAME: turnouser
      SPRING_DATASOURCE_PASSWORD: turnopass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql

volumes:
  mysql_data:
